import{test,expect}from'./fixtures';

test('English and Chinese home and games pages are complete',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Quick browser games for short breaks.'})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','en');await page.goto('/zh');await expect(page.getByRole('heading',{name:'适合休息时间的免费浏览器小游戏'})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await page.goto('/zh/games');await expect(page.getByRole('heading',{name:'全部游戏',exact:true})).toBeVisible();await expect(page.getByPlaceholder('搜索游戏…')).toBeVisible()});

for(const slug of['sudoku','gem-match','fruit-match'])test(`${slug} has localized English and Chinese pages`,async({page})=>{await page.goto(`/games/${slug}`);const english=await page.locator('h1').first().textContent();expect(english).toBeTruthy();await page.goto(`/zh/games/${slug}`);await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');const chinese=await page.locator('h1').first().textContent();expect(chinese).toBeTruthy();expect(chinese).not.toBe(english);await expect(page.getByRole('heading',{name:'游戏玩法'})).toBeVisible();await expect(page.getByRole('heading',{name:'常见问题'})).toBeVisible()});

test('language switch preserves the current game path in both directions',async({page})=>{await page.goto('/games/sudoku');if(!await page.getByRole('link',{name:'中文',exact:true}).isVisible())await page.getByRole('button',{name:'Toggle menu'}).click();await page.getByRole('link',{name:'中文',exact:true}).click();await expect(page).toHaveURL(/\/zh\/games\/sudoku$/);if(!await page.getByRole('link',{name:/^(EN|English)$/}).isVisible())await page.getByRole('button',{name:'展开菜单'}).click();await page.getByRole('link',{name:/^(EN|English)$/}).click();await expect(page).toHaveURL(/\/games\/sudoku$/)});

test('Chinese Match-3 HUD, goals and theme vocabulary are localized',async({page})=>{await page.goto('/zh/games/fruit-match');await expect(page.getByRole('heading',{name:'选择关卡'})).toBeVisible();await page.getByRole('button',{name:/关卡 1.*已解锁/}).click();await expect(page.getByText('目标',{exact:true})).toBeVisible();await expect(page.getByText('分数',{exact:true}).first()).toBeVisible();await expect(page.getByRole('button',{name:'提示'})).toBeVisible();await page.goto('/zh/games/fruit-match');await page.evaluate(()=>localStorage.setItem('miniplay:fruit-match:progress',JSON.stringify({version:1,unlocked:6,records:Object.fromEntries(Array.from({length:5},(_,i)=>[i+1,{score:1000,stars:2,completed:true}]))})));await page.reload();await page.getByRole('button',{name:/关卡 6.*已解锁/}).click();await expect(page.locator('.game-stage')).toContainText('蓝莓');await expect(page.locator('.game-stage')).not.toContainText('Collect')});

test('progress storage remains shared across languages',async({page})=>{await page.goto('/games/gem-match');await page.evaluate(()=>localStorage.setItem('miniplay:gem-match:progress',JSON.stringify({version:1,unlocked:4,records:Object.fromEntries(Array.from({length:3},(_,i)=>[i+1,{score:900,stars:2,completed:true}]))})));await page.goto('/zh/games/gem-match');await expect(page.getByRole('button',{name:/关卡 4.*已解锁/})).toBeEnabled();expect(await page.evaluate(()=>localStorage.getItem('miniplay:gem-match:progress'))).toContain('"unlocked":4');expect(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.includes('zh')&&key.includes('progress')))).toBe(false)});

test('canonical, hreflang and structured data identify each language',async({page})=>{for(const entry of[{path:'/games/sudoku',canonical:'https://gamevado.com/games/sudoku',lang:'en'},{path:'/zh/games/sudoku',canonical:'https://gamevado.com/zh/games/sudoku',lang:'zh-CN'}]){await page.goto(entry.path);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',entry.canonical);await expect(page.locator('link[rel="alternate"][hreflang="en"]')).toHaveAttribute('href','https://gamevado.com/games/sudoku');await expect(page.locator('link[rel="alternate"][hreflang="zh-CN"]')).toHaveAttribute('href','https://gamevado.com/zh/games/sudoku');await expect(page.locator('link[rel="alternate"][hreflang="x-default"]')).toHaveAttribute('href','https://gamevado.com/games/sudoku');const schema=(await page.locator('script[type="application/ld+json"]').allTextContents()).join(' ');expect(schema).toContain(`"inLanguage":"${entry.lang}"`)}});

test('sitemap contains both language sets and no /en paths',async({page})=>{const response=await page.request.get('/sitemap.xml'),xml=await response.text();for(const path of['/zh','/zh/games','/zh/games/sudoku','/zh/games/gem-match','/zh/games/fruit-match','/zh/games/match-3'])expect(xml).toContain(`https://gamevado.com${path}`);expect(xml).not.toContain('gamevado.com/en/')});

test('Chinese analytics keeps the original game slug and adds locale once',async({page})=>{test.skip(!process.env.NEXT_PUBLIC_GA_ID,'Run with analytics test id.');await page.goto('/zh/games/gem-match');await page.waitForFunction(()=>typeof window.gtag==='function');await page.evaluate(()=>{const w=window as unknown as{events:unknown[];gtag:Window['gtag']};w.events=[];w.gtag=(command,name,params)=>w.events.push({command,name,params})});await page.getByRole('button',{name:/关卡 1.*已解锁/}).click();await page.getByRole('button',{name:'提示'}).click();const cells=await page.locator('[data-hint="true"]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-cell')));for(const index of cells)await page.locator(`[data-cell="${index}"]`).click();const starts=await page.evaluate(()=>(window as unknown as{events:Array<{name:string;params:{game_slug:string;locale?:string}}>}).events.filter(event=>event.name==='game_start'));expect(starts).toHaveLength(1);expect(starts[0].params).toMatchObject({game_slug:'gem-match',locale:'zh-CN'})});

test('Chinese pages and navigation fit narrow mobile widths',async({page})=>{for(const width of[375,320])for(const path of['/zh','/zh/games','/zh/games/gem-match']){await page.setViewportSize({width,height:812});await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'展开菜单'}).click();await expect(page.getByRole('link',{name:'English',exact:true})).toBeVisible()}});

test('Chinese unknown paths use the localized 404',async({page})=>{const response=await page.goto('/zh/不存在');expect(response?.status()).toBe(404);await expect(page.getByRole('heading',{name:'页面不存在'})).toBeVisible();await expect(page.getByRole('link',{name:'返回游戏'})).toHaveAttribute('href','/zh/games')});
