import{test,expect}from'./fixtures';

const categories=['arcade','action','2-player','puzzle','match-3','casual','strategy','brain','card'];

test('category registry powers every English and Chinese category route',async({page})=>{for(const slug of categories){for(const prefix of['','/zh']){const response=await page.goto(`${prefix}/category/${slug}`);expect(response?.status(),`${prefix}/category/${slug}`).toBe(200);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',new RegExp(`${prefix}/category/${slug}$`))}}});

test('multi-category assignments are reflected without duplicate lists',async({page})=>{await page.goto('/category/action');for(const slug of['tank-duel','pixel-fighters','galaxy-strike','neon-runner','fruit-slash','breakout'])await expect(page.locator(`a[href="/games/${slug}"]`)).toBeVisible();await page.goto('/category/match-3');await expect(page.locator('article')).toHaveCount(7);await page.goto('/category/strategy');for(const slug of['2048-merge','number-merge','sudoku','solitaire','connect-four'])await expect(page.locator(`a[href="/games/${slug}"]`)).toBeVisible()});

test('2 Player is a real crawlable category with true local multiplayer games',async({page})=>{await page.goto('/category/2-player');await expect(page.getByRole('heading',{name:'2 Player Games',exact:true})).toBeVisible();await expect(page.locator('article')).toHaveCount(2);for(const slug of['tank-duel','pixel-fighters'])await expect(page.locator(`a[href="/games/${slug}"]`)).toBeVisible();await page.goto('/zh/category/2-player');await expect(page.getByRole('heading',{name:'双人游戏',exact:true})).toBeVisible();await expect(page.locator('article')).toHaveCount(2)});

test('desktop and mobile navigation expose portal categories and language switch',async({page})=>{await page.setViewportSize({width:1366,height:768});await page.goto('/');const header=page.locator('header');for(const label of['Games','Categories','2 Player','Match-3'])await expect(header.getByRole('link',{name:label,exact:true})).toBeVisible();await page.setViewportSize({width:320,height:812});await page.getByRole('button',{name:'Toggle menu'}).click();for(const label of['Games','Categories','2 Player','Match-3','Action','Strategy','中文'])await expect(header.getByRole('link',{name:label,exact:true}).last()).toBeVisible()});

test('category indexes and sitemap expose both locale trees',async({page})=>{for(const path of['/categories','/zh/categories']){await page.goto(path);await expect(page.locator('h1')).toBeVisible();expect(await page.locator('article').count()).toBe(9)}const xml=await(await page.request.get('/sitemap.xml')).text();for(const slug of categories){expect(xml).toContain(`/category/${slug}`);expect(xml).toContain(`/zh/category/${slug}`)}});
